require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Exclude:
    - 'config/application.rb'
    - 'db/migrate/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*.rb'
